### PR TITLE
Raise errors instead of throwing

### PR DESCRIPTION
**Pull request by ericmj**
It is not idiomatic to leak throws from an API.

The throws seem to originating from the following commit: https://github.com/davisp/jiffy/commit/a2a7bc91afe8d38553afad6dd721da217666760c.

> The encode and decode functions now return the value directly without
> being wrapped in a tuple on success. If there is an error, it is
> thrown. This is to more closely match the semantics of term_to_binary
> and binary_to_term.

It is not the semantics of `term_to_binary` and `binary_to_term` to throw - they raise errors.

### CODE REVIEW

**Comment by ericmj** [comment]
Ping?

**Comment by davisp** [comment]
Oops, forgot to update, I am planning on making this change as part of a 1.0 release but want to make sure I don't leave any other breaking changes that should also be changed as well so am still contemplating if there are other minor API bits that could be improved.

**Comment by ericmj** [comment]
Ping?

**Comment by davisp** [comment]
Hiya. This is still on my radar. I just need to figure out what else I might need/want to break for a 1.0 release. This will be nice to have but its not enough on its own to push the breaking changes.

**Comment by ericmj** [comment]
Ping?

**Pull request merged**
