### PR TITLE
Use port_compiler and drop previous compile hook

### PR DESCRIPTION
**Pull request by filmor**
Also drops the explicit `-lstdc++` ldflag.

### CODE REVIEW

**Comment by filmor** [comment]
This fails right now because apparently `rebar` doesn't properly detect whether it needs to use `g++` or `gcc` as a linker while `port_compiler` does. I'll try to fix this.

**Comment by filmor** [comment]
Apparently this requires https://github.com/rebar/rebar/pull/617 which was included in 2.6.3. Is there any particular reason why you are still using 2.0.0?

**Comment by NelsonVides** [comment]
@davisp hey, is there any reason why we don't move jiffy to rebar3+pc? As I said on the Erlang forums in regard to this topic, right now every other OTP release we need to recompile enc, update jiffy, update any dependency that uses jiffy, update any other dependency that uses any of those dependencies... which makes it all very convoluted and increases a lot the maintenance effort.

I think it would be best for maintenance to stick to straight-forward and portable supply-chain pipelines, can we please apply this PR and make a new release, or is there any reason against that?

**Comment by davisp** [comment]
@NelsonVides The main reason I went with the `enc` approach was that the `pc` plugin didn't work in some scenarios when we originally tried it. If memory serves, the issue was that a dependency of a dependency (where jiffy comes in a lot of times) wouldn't download the plugin properly.

I'm also quite keen to keep backwards compatibility as far as possible. I've only had to recompile it once since I started using it when one recent-ish release dropped support for anything less than R15. I'll get 25 compiled today and see how far back they've dropped support for this time. If its close enough and the other issues with `pc` are fixed we can make the change.

**Comment by davisp** [comment]
Hey all,

Given that Erlang 25 has decided to nuke support for anything older than 22 I'm giving the port_compiler approach a whirl. So far I'm not able to get Jiffy to compile even as a direct dependency because of the missing port compiler plugin. Is there something I'm doing wrong? I've put up a test app here [1].

[1] https://github.com/davisp/jtapp1

**Comment by aboroska** [comment]
@davisp @filmor Yes, the difference is that if jiffy's config adds `pc` in `project_plugins` then the users of jiffy also need to explicitly add `pc`. If jiffy's config adds pc in `plugins`, then the users don't have to add `pc` themselves.

**Comment by davisp** [comment]
Here's a branch [1] that I have so far. While working through this approach I've also managed to get Erlang VMs compiled all the way back to R15B03-1. On Monday, I'll work on a script to go back through each major VM version and test compiling both directly and via dependency declarations. Once I have that setup and verified that its working I'll push a new version to hex.pm.

[1] https://github.com/davisp/jiffy/compare/pc-test

**Comment by tsloughter** [comment]
Right, `project_plugins` are for plugins you only want when developing on the project and not when it is being built. So linting for example.

**Comment by NelsonVides** [comment]
Hey there, follow up on this, any progress, or any help needed? :)

**Comment by davisp** [comment]
I'm working on this today. We had some unseasonably warm weather yesterday that I took advantage of to do some work outdoors. Assuming no surprises I should have new packages pushed this afternoon.

**Comment by davisp** [comment]
I've uploaded 1.1.0 to hex.pm which should fix this. Please open new issues if anything breaks as a consequence.

**Comment by filmor** [comment]
Another important part of this PR was using `g++` to properly link `libstdc++`, I'll create a new PR for this.

**Comment by davisp** [comment]
@filmor I dropped that on purpose as its not part of the build system PR. If you have a motivating error for it though I'm all ears.

**Comment by dch** [comment]
so getting my head around this, we'd have a hard dependency in general on jiffy/enc/pc etc pre 22 and post 22?

FWIW this doesn't seem unreasonable to me, so long as we can always build the toolchain with OTP22, and use it on OTP22+ without issue.

**Pull request closed without merging**
