### PR TITLE
Add replace_undefined and escape_forward_slashes

### PR DESCRIPTION
**Pull request by ratelle**
I've kept use_nil for backward compatibility. If use_nil and replace_undefined are used together, jiffy:decode will throw a bardarg.

### CODE REVIEW

**Comment by lpgauth** [comment]
:+1:

**Comment by lpgauth** [comment]
@davisp ping?

**Comment by haguenau** [comment]
:heart:

**Comment by davisp** [comment]
My bad for waiting so long to get to this. Got caught up at work and lost it in the inbox noise.

**Comment by ratelle** [comment]
@davisp Looks better?

**Comment by davisp** [comment]
Awesome work. Thanks for the patches!

**Pull request merged**
