### PR TITLE
Catch and re-throw big exponent exceptions

### PR DESCRIPTION
**Pull request by srenatus**
```
$ rebar3 shell
===> Verifying dependencies...
===> Compiling jiffy
Erlang/OTP 18 [erts-7.3] [source] [64-bit] [smp:8:8] [async-threads:0] [hipe] [kernel-poll:false]

Eshell V7.3  (abort with ^G)
1> jiffy:decode(<<"[1e310]">>).
** exception error: an error occurred when evaluating an arithmetic expression
     in function  math:pow/2
        called as math:pow(10,310)
     in call from jiffy:finish_decode/1 (jiffy/_build/default/lib/jiffy/src/jiffy.erl, line 118)
     in call from jiffy:finish_decode_arr/2 (jiffy/_build/default/lib/jiffy/src/jiffy.erl, line 149)
2> jiffy:decode(<<"[0.2e310]">>).
** exception error: bad argument
     in function  list_to_float/1
        called as list_to_float("0.2e310")
     in call from jiffy:finish_decode/1 (jiffy/_build/default/lib/jiffy/src/jiffy.erl, line 120)
     in call from jiffy:finish_decode_arr/2 (jiffy/_build/default/lib/jiffy/src/jiffy.erl, line 149)
3>
```

That `310` could depend on my machine, since `math:pow/2` says it's a limitation coming from libc.

With this change, this still throws an exception, but it doesn't come
from math or erlang, but jiffy:

```
1> jiffy:decode(<<"[1e310]">>).
** exception throw: {error,{exponent_too_big,310}}
     in function  jiffy:finish_decode/1 (/Users/stephan/Misc/radamsa-epmd/jiffy/_build/default/lib/jiffy/src/jiffy.erl, line 121)
     in call from jiffy:finish_decode_arr/2 (/Users/stephan/Misc/radamsa-epmd/jiffy/_build/default/lib/jiffy/src/jiffy.erl, line 157)
2>
```

Signed-off-by: Stephan Renatus <srenatus@chef.io>

### CODE REVIEW

**Comment by davisp** [comment]
This looks mostly fine to me. The only thing though is whether we're being overly specific with the error message. I wonder if there's a standard/math error that relates to range. For instance, -310 should theoretically also be an error but "too large" is a bit backwards. I'd also wonder about To large of a fractional part which again would be a "too small" type error.

**Comment by davisp** [comment]
And perhaps just {error, {range, Value}} is good enough? I was originally thinking of ERANGE errno.

**Comment by srenatus** [comment]
I've changed it to `range` instead of `big_exponent`. However, both `1e-3000` and `0.1e-3000` actually decode fine to `0.0`. 🤷‍♂️

**Comment by davisp** [comment]
Merged by hand.

**Pull request closed without merging**
