### PR TITLE
Escape forward slashes

### PR DESCRIPTION
**Pull request by ratelle**

### CODE REVIEW

**Comment by davisp** [comment]
Whoa, my bad for not seeing this.

The use_undefined isn't a bad change, though I would change it slightly, instead of passing use_nil, or use_undefined, I'd do something like {replace_null, Term} where Term would be inserted anywhere that null was found (defaulting to null).

What's the use case for forward slash escapes? I originally had that but removed it due to popular request (URLs notably were icky with that enabled). I'd be open to having it configurable if there's a use case where it makes sense.

**Comment by minaguib** [comment]
@davisp Re forward slash escaping, it's a double-edged sword.

The use case for making it optionally enabled is when you're escaping JSON that will then be included in an HTML document (within < script > ) tags.  If the data being encoded contains a JSON string that itself has "..... < / s c r i p t > ....." the net effect is:

    <html>
    <script>
      var foo = {
        "x": "something </script> here"
      };
    </script>
    </html>

The problem is that most web browsers are not capable from distinguishing the < / s c r i p t > inside the script block's string from the real one intended to terminate the script, and most stop feeding the javascript to the javascript interpreter halfway through that string, causing both a JS error as well as rendering the rest of the script as HTML text.

Enabling escaping forward slashes causes the string to become "something <\/script> here" which avoids this hiccup.

**Comment by davisp** [comment]
Huh. Good enough for me. I'd add that commit if you want to add a few tests.

**Comment by ratelle** [comment]
@davisp : I initially opened that pull request by mistake and closed it immediately. I agree with the {replace_null, Term}, that was initially my plan to do that. I will make the necessary corrections, add some tests and reopen a pull request.

**Comment by davisp** [comment]
Ah, gotchya. I looked at the commit dates and thought i'd missed the PR for a month and hadn't seen it yet.

**Comment by lpgauth** [comment]
I did send a pull request for use_undefined 27 days ago... https://github.com/davisp/jiffy/pull/87

**Pull request closed without merging**
